version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    working_directory: ~/repo
    environment:
      BUNDLER_VERSION: 1.17.3
    steps:
      - checkout
      - run: gem install bundler:1.17.3
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: run specs
          command: bundle exec rspec
