version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    working_directory: ~/repo
    environment:
      BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - run: gem install bundler:2.0.1
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: run specs
          command: bundle exec rspec
